bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - left_wheel_hinge
        - right_wheel_hinge
      PitchGain: 0.0
      PitchDotGain: 0.05
      YawGain: 0.0
      YawDotGain: 0.0
      WheelGain: 0.0000
      WheelDotGain: 0.005 #0.025
      WheelIntegralGain: 0.00000
      WheelIntegralSaturation: 1000.0
      PendulumStateAlpha: 0.5
      WheelStateAlpha: 0.5
      EffortPendulumAlpha: 0.05
      EffortWheelAlpha: 0.05
      MotorEffortMax: 0.4
      RollOffset: -2.895
