bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      InSim: false
      StartingTiltSafetyLimitDegrees: 10.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.2
      MotorEffortToTorqueSimFactor: 1.0 # Should be set to 1.0 for HW
      WheelVelocityAdjustment: 0.05
      MadgwickFilterGain: 0.35
      MeasuredTiltFilterGain: 0.15
      MeasuredTiltDotFilterGain: 0.15
      MeasuredHeadingFilterGain: 0.5
      MeasuredTurnRateFilterGain: 0.1
      LeftWheelVelocityFilterGain: 0.15
      RightWheelVelocityFilterGain: 0.15
      DesiredForwardVelocityFilterGain: 0.01
      DesiredTurnRateFilterGain: 0.01
      MaxVelocityCmd: 0.35  # XX mph
      MaxTurnRateCmd: 3.25 # XX deg/s
      WheelRadiusMeters: 1.0
      VelocityCmdScale: 2.65
      TurnCmdScale: 12.5
      VelocityControlKp: 0.2
      VelocityControlKi: 0.001
      VelocityControlAlphaFilter: 0.15
      VelocityControlMaxIntegralOutput: 0.8
      VelocityControlOutputLimitDegrees: 8.0
      TiltControlKp: 1.0
      TiltControlKd: 0.05
      TiltControlAlphaFilter: 0.15
      TiltOffset: 0.10
      TiltDotOffset: -0.1457
      RollDotOffset: 0.0
      YawDotOffset: -0.0137
      TurningControlKp: 0.08
      TurningControlKi: 0.01
      TurningControlKd: 0.075
      TurningOutputFilter: 0.5

