bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - left_wheel_hinge
        - right_wheel_hinge
      PitchGain: 1.5
      PitchDotGain: 0.075
      YawGain: 0.0
      YawDotGain: 0.0
      WheelGain: 0.00
      WheelDotGain: 0.0005
      WheelIntegralGain: 0.00000
      WheelIntegralSaturation: 1000.0
      PendulumStateAlpha: 0.25
      WheelStateAlpha: 0.25
      EffortPendulumAlpha: 0.5
      EffortWheelAlpha: 0.05
      MotorEffortMax: 0.4
      RollOffset: -2.835
      MaximumPitch: 0.15
      WheelVelocityAdjustment: 0.4
