bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      StartingTiltSafetyLimitDegrees: 4.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.2
      MotorEffortToTorqueSimFactor: 0.832 # Should be set to 1.0 for HW
      WheelBaseDistance: 0.4
      WheelVelocityAdjustment: 0.05
      MeasuredTiltFilterGain: 0.0
      MeasuredTiltDotFilterGain: 0.0
      MeasuredHeadingFilterGain: 0.0
      MeasuredTurnRateFilterGain: 0.4
      LeftWheelVelocityFilterGain: 0.4
      RightWheelVelocityFilterGain: 0.4
      VelocityCmdScale: 1.25
      TurnCmdScale: 0.2
      VelocityControlKp: 1.0
      VelocityControlKi: 0.015
      VelocityControlAlphaFilter: 0.0
      VelocityControlMaxIntegralOutput: 0.076
      VelocityControlOutputLimitDegrees: 5.0
      TiltControlKp: 2.0
      TiltControlKd: 0.25
      TiltControlAlphaFilter: 0.0
      TurningControlKp: 1.0
      TurningControlKi: 0.0
      TurningControlKd: 0.0
