bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      PitchGain: 0.20
      PitchDotGain: 0.0005
      YawGain: 0.0
      YawDotGain: 0.0
      WheelGain: -0.00025
      WheelDotGain: 0.0
      WheelIntegralGain: 0.00000
      WheelIntegralSaturation: 1000.0
      PendulumStateAlpha: 0.5
      WheelStateAlpha: 0.5
      EffortPendulumAlpha: 0.05
      EffortWheelAlpha: 0.95
      MotorEffortMax: 0.4