bobble:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100

    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - left_wheel_hinge
        - right_wheel_hinge
