bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      InSim: false
      StartingTiltSafetyLimitDegrees: 10.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.2
      MotorEffortToTorqueSimFactor: 1.0 # Should be set to 1.0 for HW
      WheelVelocityAdjustment: 0.05
      MadgwickFilterGain: 0.35
      MeasuredTiltFilterGain: 0.15
      MeasuredTiltDotFilterGain: 0.15
      MeasuredHeadingFilterGain: 0.5
      MeasuredTurnRateFilterGain: 0.1
      LeftWheelVelocityFilterGain: 0.5
      RightWheelVelocityFilterGain: 0.5
      DesiredForwardVelocityFilterGain: 0.1
      DesiredTurnRateFilterGain: 0.1
      MaxVelocityCmd: 1.25  # 3 mph
      MaxTurnRateCmd: 2.6 # 150 deg/s
      WheelRadiusMeters: 1.0
      VelocityCmdScale: 2.85
      TurnCmdScale: 20.0
      VelocityControlKp: 0.20
      VelocityControlKi: 0.001
      VelocityControlAlphaFilter: 0.15
      VelocityControlMaxIntegralOutput: 0.08
      VelocityControlOutputLimitDegrees: 10.0
      TiltControlKp: 1.0
      TiltControlKd: 0.05
      TiltControlAlphaFilter: 0.05
      TiltOffset: 0.10
      TiltDotOffset: -0.1457
      RollDotOffset: 0.0
      YawDotOffset: -0.0137
      TurningControlKp: 0.1
      TurningControlKi: 0.0
      TurningControlKd: 0.0
      TurningOutputFilter: 0.5

