bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      StartingTiltSafetyLimitDegrees: 4.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.08
      MotorEffortToTorqueSimFactor: 0.832 # Should be set to 1.0 for HW
      MeasuredTiltFilterGain: 0.3
      MeasuredTiltDotFilterGain: 0.3
      LeftWheelVelocityFilterGain: 0.05
      VelocityControlKp: 0.0
      VelocityControlKi: 0.000
      VelocityControlAlphaFilter: 0.0
      VelocityControlMaxIntegralOutput: 0.076
      VelocityControlOutputLimitDegrees: 5.0
      TiltControlKp: 3.5
      TiltControlKd: 0.075
      TiltControlAlphaFilter: 0.01
      HoldHeadingControlKp: 0.0
      HoldHeadingControlKd: 0.0
      TurningControlKp: 0.0
      TurningControlKi: 0.0
      TurningControlKd: 0.0
