bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      InSim: true
      StartingTiltSafetyLimitDegrees: 10.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.2
      MotorEffortToTorqueSimFactor: 0.832
      WheelVelocityAdjustment: 1.0
      MadgwickFilterGain: 0.015
      MeasuredTiltFilterGain: 0.15
      MeasuredTiltDotFilterGain: 0.15
      MeasuredHeadingFilterGain: 0.5
      MeasuredTurnRateFilterGain: 0.1
      LeftWheelVelocityFilterGain: 0.25
      RightWheelVelocityFilterGain: 0.25
      DesiredForwardVelocityFilterGain: 0.25
      DesiredTurnRateFilterGain: 0.25
      MaxVelocityCmd: 1.25 # 3 mph
      MaxTurnRateCmd: 3.141 # 90 deg/s
      WheelRadiusMeters: 0.05
      VelocityCmdScale: 3.75
      TurnCmdScale: 20.0
      VelocityControlKp: 0.2
      VelocityControlKi: 0.001
      VelocityControlAlphaFilter: 0.45
      VelocityControlMaxIntegralOutput: 0.5
      VelocityControlOutputLimitDegrees: 12.0
      TiltControlKp: 1.0
      TiltControlKd: 0.12
      TiltControlAlphaFilter: 0.05
      TiltOffset: 0.0
      TiltDotOffset: 0.0
      RollDotOffset: 0.0
      YawDotOffset: 0.0
      TurningControlKp: 0.075
      TurningControlKi: 0.0
      TurningControlKd: 0.0
      TurningOutputFilter: 0.5

