bobble:
    bobble_balance_controller:
      type: bobble_controllers/BobbleBalanceController
      joints:
        - right_wheel_hinge
        - left_wheel_hinge
      InSim: false
      StartingTiltSafetyLimitDegrees: 4.0
      MaxTiltSafetyLimitDegrees: 20.0
      MotorEffortMax: 0.2
      MotorEffortToTorqueSimFactor: 1.0 # Should be set to 1.0 for HW
      WheelVelocityAdjustment: 0.05
      MadgwickFilterGain: 0.20
      MeasuredTiltFilterGain: 0.025
      MeasuredTiltDotFilterGain: 0.025
      MeasuredHeadingFilterGain: 0.0
      MeasuredTurnRateFilterGain: 0.10
      LeftWheelVelocityFilterGain: 0.150
      RightWheelVelocityFilterGain: 0.150
      VelocityCmdScale: 7.5
      TurnCmdScale: 3.75
      VelocityControlKp: 0.025
      VelocityControlKi: 0.0
      VelocityControlAlphaFilter: 0.45
      VelocityControlMaxIntegralOutput: 0.076
      VelocityControlOutputLimitDegrees: 5.0
      TiltControlKp: 2.0
      TiltControlKd: 0.15
      TiltControlAlphaFilter: 0.05
      TiltOffset: 2.88
      TurningControlKp: 0.3
      TurningControlKi: 0.0
      TurningControlKd: 0.0
      TurningOutputFilter: 0.5

